import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import { Inter } from 'next/font/google'
import Providers from './redux/provider'
import Navbar from './components/Navbar'
import Foter from './components/Foter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'weblog-star',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>
         <Navbar/>
         {children}
         <Foter/>
       </Providers>
      </body>
    </html>
  )
}
